"""empty message

Revision ID: ae3c951539a2
Revises: 
Create Date: 2024-04-05 11:56:10.310127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3c951539a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('fecha_de_registro', sa.String(length=120), nullable=False),
    sa.Column('pregunta1', sa.String(length=120), nullable=False),
    sa.Column('respuesta1', sa.String(length=120), nullable=False),
    sa.Column('pregunta2', sa.String(length=120), nullable=False),
    sa.Column('respuesta2', sa.String(length=120), nullable=False),
    sa.Column('pregunta3', sa.String(length=120), nullable=False),
    sa.Column('respuesta3', sa.String(length=120), nullable=False),
    sa.Column('fecha_de_questionario', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
