"""empty message

Revision ID: f63d18a47d3f
Revises: 
Create Date: 2024-04-06 08:26:27.044816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63d18a47d3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('fecha_de_registro', sa.String(length=120), nullable=False),
    sa.Column('pregunta1', sa.String(length=120), nullable=True),
    sa.Column('respuesta1', sa.String(length=120), nullable=True),
    sa.Column('pregunta2', sa.String(length=120), nullable=True),
    sa.Column('respuesta2', sa.String(length=120), nullable=True),
    sa.Column('pregunta3', sa.String(length=120), nullable=True),
    sa.Column('respuesta3', sa.String(length=120), nullable=True),
    sa.Column('fecha_de_cuestionario', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
